apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-ai-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: enterprise-ai-api

  template:
    metadata:
      labels:
        app: enterprise-ai-api

    spec:
      containers:
        - name: enterprise-ai-api

          image: ambhoj10/enterprise-ai-api:v1

          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
